# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Scripter-Plugin-JavaScript-SpiderMonkey
version:      0.002
version_from: lib/WWW/Scripter/Plugin/JavaScript/SpiderMonkey.pm
installdirs:  site
requires:
    constant:                      1.03
    constant::lexical:             0
    Hash::Util::FieldHash::Compat: 0
    HTML::DOM::Interface:          0
    JavaScript:                    1.12
    lib:                           0
    Scalar::Util:                  0
    strict:                        0
    Test::More:                    0
    URI::file:                     0
    warnings:                      0
    WWW::Scripter:                 0.016
    WWW::Scripter::Plugin::JavaScript: 0.005

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
